@startuml
hide footbox
title RDCU - Selectionner un questionnaire

participant ":QuestionnaireController" as controller
participant ":QuestionnaireModele" as questionnaireModele
participant "reponseQuestionnaire:ReponseQuestionnaire" as reponseQuestionnaire

-> controller : selectionnerQuestionnaire(nom:String):Questionnaire
note right: GRASP: Controller
activate controller

controller -> questionnaireModele : recupererQuestionnaireParNom(nom:String):Questionnaire
note right: GRASP: Expert
activate questionnaireModele

questionnaireModele -> reponseQuestionnaire ** : create
note right: GRASP: Createur
note over reponseQuestionnaire
On creer une instance de ReponseQuestionnaire
pour stocker les réponses de l'étudiant pour ce questionnaire
et chaque réponse de l'étudiant est ajoutée à la liste de réponses
dans ReponseQuestionnaire
et on corriger à la fin en comparant les réponses
de l'étudiant avec les réponses correctes du questionnaire
end note

questionnaireModele --> controller : detailsQuestionnaire:Questionnaire
deactivate questionnaireModele

<-- controller : detailsQuestionnaire:Questionnaire
deactivate controller

@enduml
