@startuml
title CU02d - Supprimer une question
actor ":Enseignant" as e
participant ":Systeme" as s

e->s : consulterQuestionsCours(groupId : String)
s-->>e : Liste des questions associees au cours

e->s : supprimerQuestion(groupId :String, nom : String)
alt Question existante
	s-->>e : Valeurs actuelles de la question et demande de confirmation
	e->s : confirmerSuppression()
	alt Suppression reussie
		s-->>e : Message confirmant la suppression et nouvelle liste de questions
	else Erreur de suppression
		s-->>e : Signalement d'erreur
	end alt
end alt
@enduml