@startuml
title CU02a -Ajouter une question
actor ":Enseignant" as e
participant ":Systeme" as s
' Ajout des Pre conditions ici si nécessaire
e->s : consulterQuestionsCours(groupId : String)
s-->>e : Liste des questions associees au cours
loop Tant que l'enseignant veut ajouter des questions
alt Ajout de Question Vrai ou Faux
e->s : ajouterQuestionVraiFaux(nom : String, enonce : String, reponse : bool, retroactionValide : String, retroactionInvalide : String, tags : String[])
else Ajout d'autre type de question
 e->s : ajouterQuestionAutreType(nom : String, enonce : String, type : String, retroactionValide : String, retroactionInvalide : String, tags : String[])
end alt

alt Nom de question unique
    s-->>e : Liste des questions associees au cours mise a jour et confirmation de l'ajout
else Nom de question deja utilise
    s-->>e : Signalement d'erreur
end alt
end loop

@enduml