@startuml
title CU02c - Modifier une question
actor ":Enseignant" as e
participant ":Systeme" as s
e->s : consulterQuestionsCours(groupId : String)
s-->>e : Liste des questions associees au cours
'Noter qu'il faudrait 2 boutons 1 pour details, un pour modifier
e->s : modifierQuestion(nom : String)
s-->>e : Détails de la question (Type, Nom,\nÉnoncé, Vérité, \nRétroaction pour la bonne réponse, \nRétroaction pour la mauvaise réponse, tags)
e->s : modifierQuestion(nom : String, enonce : String, type : String, \nretroactionValide : String, retroactionInvalide : String, tags : String[])
alt Nom de question unique
s-->>e : Question modifiée et message de confirmation
else Nom de question deja utilise 
s-->>e : Signalement d'erreur
end alt
@enduml