@startuml
title CU02a - Ajouter une question
actor ":Enseignant" as e
participant ":Systeme" as s

e->s : consulterQuestionsCours(groupId : String)
s-->>e : Liste des questions associees au cours

loop Tant que l'enseignant veut ajouter des questions
alt Ajout de Question Vrai ou Faux
e->s : ajouterQuestionVraiFaux(nom : String, enonce : String, reponse : bool, retroactionValide : String, retroactionInvalide : String, tags : String[])
else Ajout de Question a choix multiple
 e->s : ajouterQuestionChoixMultiple(nom : String, enonce : String, reponses : String[], retroactionValide : String, retroactionInvalide : String, tags : String[],seulementUnChoix : bool)
else Ajout de Question a reponse courte
 e->s : ajouterQuestionReponseCourte(nom : String, enonce : String, reponse : String, retroactionValide : String, retroactionInvalide : String, tags : String[])
else Ajout de Question a reponse numerique
 e->s : ajouterQuestionReponseNumerique(nom : String, enonce : String, reponse : number, retroactionValide : String, retroactionInvalide : String, tags : String[])
else Ajout de Question essai
    e->s : ajouterQuestionEssai(nom : String, enonce : String, retroactionValide : String, retroactionInvalide : String, tags : String[])
else Ajout de Question de mise en correspondance
    e->s : ajouterQuestionMiseCorrespondance(nom : String, enonce : String, pairesQuestion : String[], pairesReponse : String[], retroactionValide : String, retroactionInvalide : String, tags : String[])
end alt

alt Nom de question unique
    s-->>e : Confirmation d'ajout et details de la question creee
else Nom de question deja utilise ou donnees invalides
    s-->>e : Signalement d'erreur
end alt
end loop

@enduml