@startuml
hide footbox
title RDCU – Sélectionner une question à modifier

participant "qc:QuestionsController" as QC
participant "cs:CoursStore" as CS

-> QC : selectionnerModifierQuestion(groupId : String, nom : String)
note right: GRASP: Controller
activate QC

QC -> CS : recupererQuestionParNom(groupId : String, nom : String)
activate CS
CS --> QC : question : Question
deactivate CS

<-- QC : ouvrirFormulaireModification(question)

deactivate QC

@enduml