@startuml
hide footbox
title RDCU - Modifier une question vrai/faux

participant "qc:QuestionsController" as QC
participant "cm:CoursModele" as CM
participant "q:QuestionVraiFauxModele" as Q

-> QC : modifierQuestionVraiFaux(type: String, nom: String, enonce : String, retroactionValide : String, retroactionInvalide : String, tags : String[], reponse : Boolean)
note right: GRASP: Controller (Le nom de la fonction dans QuestionController est modifierQuestion)
activate QC

QC -> CM : obtenirQuestionParNom(idGroupe : String, nomOriginal : String)
note right: GRASP: Expert
activate CM
CM --> QC : questionExistante : AnyQuestion
deactivate CM

QC -> QC ++: validerChampsObligatoires(type:String, nom:String, enonce:String)
note right: GRASP: Expert
deactivate QC

QC -> CM : validerNomQuestionUnique(idGroupe: String, nomFinal: String, nomOriginal: String)
note right: GRASP: Expert
activate CM
CM --> QC : nomExiste : boolean
deactivate CM

alt Nom unique et donnees valides
    QC -> QC : creerQuestionAutreType(type: string, nom: string, enonce: \nstring,retroactionValide: string, \nretroactionInvalide: string, tags: string[], autresDonnees: Record<string, unknown>)


  QC -> QC : lireBooleen(reponse)
  note right: GRASP: Expert

  create Q
  QC -> Q : <<create>> QuestionVraiFauxModele(nom, enonce,\n retroactionValide, retroactionInvalide, tags, reponse, retroactionValide)
  note right: GRASP: Creator
  activate Q
  deactivate Q

  QC -> CM : modifierQuestionDuCours(idGroupe : String, nomOriginal : String, q)
  note right: GRASP: Expert
  activate CM
  deactivate CM

  <-- QC : afficherConfirmationModification
else Nom deja utilise ou donnees invalides
  <-- QC : signalerErreurModification
end

deactivate QC

@enduml