@startuml
hide footbox
title RDCU - ajouterQuestionParType

participant "qc:QuestionsController" as QC
participant "cs:CoursStore" as CS
participant "q:Question" as Q

-> QC : ajouterQuestionParType(nom : String, enonce : String, type : String,\n retroactionValide : String, retroactionInvalide : String, tags : String[])
note right: GRASP: Controller
activate QC

QC -> CS : validerNomQuestionUnique(groupId: String, nom: String)
activate CS
CS --> QC : nomExiste:boolean
deactivate CS

alt Nom de question unique
  create Q
  QC -> Q : <<create>> creerQuestionAutreType(nom, enonce, type,\n retroactionValide, retroactionInvalide, tags)
  activate Q
  deactivate Q

  QC -> CS : addQuestion(q)
  activate CS
  deactivate CS

  <-- QC : confirmationAjout(listeQuestions):String
else Nom de question deja utilise
  <-- QC : signalerErreurNomExistant():String
end

deactivate QC

@enduml
