@startuml
title RDCU pour Demarrer la gestion des questions
participant ":Enseignant" as e
participant "c:Cours" as c

-->e : gestionQuestion()
activate e
    e->c : recupererQuestions() : Question[]
    activate c
deactivate c
deactivate e
@enduml