@startuml
hide footbox
title RDCU - Ajouter une question mise en correspondance

participant "qc:QuestionsController" as QC
participant "cs:CoursStore" as CS
participant "q:QuestionMiseEnCorrespondance" as Q

-> QC : ajouterQuestionMiseEnCorrespondance(nom : String, enonce : String,\n paires : PairDeCorrespondance[], retroactionValide : String,\n retroactionInvalide : String, tags : String[])
note right: GRASP: Controller
activate QC

QC -> QC : validerDonnees(nom, enonce, paires, tags)
note right: GRASP: Expert

QC -> CS : existeNomQuestion(groupId : String, nom : String)
note right: GRASP: Expert
activate CS
CS --> QC : nomExiste : boolean
deactivate CS

alt Donnees valides et nom unique
  create Q
  QC -> Q : <<create>> QuestionMiseEnCorrespondance(nom, enonce, paires,\n retroactionValide, retroactionInvalide, tags)
  note right: GRASP: Creator
  activate Q
  deactivate Q

  QC -> CS : ajouterQuestionAuCours(groupId : String, q)
  note right: GRASP: Expert
  activate CS
  deactivate CS

  <-- QC : confirmationAjout(questionCreee)
else Nom deja utilise ou donnees invalides
  <-- QC : signalerErreurAjoutQuestion()
end

deactivate QC
@enduml
