@startuml
hide footbox
title RDCU pour Ajouter une question Vrai ou Faux

participant "qc:QuestionsController" as QC
participant "cs:CoursStore" as CS
participant "q:QuestionVraiFaux" as Q

-> QC : ajouterQuestionVraiFaux(nom : String, enonce : String,\n reponse : bool, retroactionValide : String,\n retroactionInvalide : String, tags : String[])
note right: GRASP: Controller
activate QC

QC -> CS : validerNomQuestionUnique(groupId: String, nom: String)
activate CS
CS --> QC : nomExiste:boolean
deactivate CS

alt Nom de question unique
    create Q
    QC -> Q : <<create>> QuestionVraiFaux(nom, enonce, reponse,\n retroactionValide, retroactionInvalide, tags)
    activate Q
    deactivate Q

    QC -> CS : addQuestion(q)
    activate CS
    deactivate CS

    <-- QC : confirmationAjout(listeQuestions):String
else Nom de question deja utilise
    <-- QC : signalerErreurNomExistant():String
end

deactivate QC
@enduml