@startuml
hide footbox
title RDCU – Sélectionner une question

participant "qc:QuestionsController" as QC
participant "cs:CoursStore" as CS

-> QC : selectionnerQuestion(groupId : String, nom : String)
note right: GRASP: Controller
activate QC

QC -> CS : recupererQuestionParNom(groupId : String, nom : String)
note right: GRASP: Expert
activate CS
CS --> QC : question : Question
deactivate CS

<-- QC : afficherInfoQuestion

deactivate QC

@enduml