@startuml
hide footbox
title RDCU – Supprimer une question (Confirmation)

participant "qc:QuestionsController" as QC
participant "cs:CoursStore" as CS

-> QC : confirmerSuppression(groupId : String, nom : String)
note right: GRASP: Controller
activate QC

QC -> CS : supprimerQuestion(groupId : String, nom : String)
activate CS
deactivate CS

QC -> CS : getQuestionsForCours(groupId: string)
activate CS
'???'
CS --> QC : questions : List<Question>
deactivate CS

'QC --> UI : afficherListeQuestions(questions):String'
<-- QC : afficherConfirmationSuppression():String
deactivate QC

@enduml