@startuml
hide footbox
title RDCU – Modifier une question

participant "ui:UIQuestionsCours" as UI
participant "qc:QuestionsController" as QC
participant "qs:QuestionsStore" as QS
participant "q:Question" as Q


-> UI : modifierQuestion(nom, enonce, type,\nretroactionValide, retroactionInvalide, tags)
activate UI

UI -> QC : modifierQuestion(groupId, nom, enonce, type,\nretroactionValide, retroactionInvalide, tags)
activate QC

QC -> Q : modifierQuestion(nom, enonce, type,\nretroactionValide, retroactionInvalide, tags)
activate Q
Q --> QC : confirmationModificationQuestion():boolean
deactivate Q

alt Nom de question unique
    QC -> QS : updateQuestion(Q)
    activate QS
    QS --> QC : confirmationModificationQuestionStore():boolean
    deactivate QS

    QC --> UI : afficherConfirmationModification(Q):String

    <-- UI : questionModifiee():String


else Nom de question deja utilise
    QC --> UI : signalerErreurNomExistant():String
    deactivate QC

    <-- UI : erreurNomNonUnique():String
    deactivate UI
end

@enduml