@startuml
hide footbox
title RDCU – Sélectionner une question à modifier

participant "ui:UIQuestionsCours" as UI
participant "qc:QuestionsController" as QC
participant "qs:QuestionsStore" as QS
participant "q:Question" as Q


-> UI : selectionnerModifierQuestion(nom : String)
activate UI

UI -> QC : selectionnerModifierQuestion(groupId : String, nom : String)
activate QC

QC -> QS : chercherInfoQuestion(groupId : String, nom : String)
activate QS
QS --> QC : question : Question
deactivate QS

activate Q
QC -> Q : getType()
Q --> QC : type:String

QC -> Q : getNom()
Q --> QC : nom:String

QC -> Q : getEnonce()
Q --> QC : enonce:String

QC -> Q : getVerite()
Q --> QC : verite:String

QC -> Q : getRetroactionBonne()
Q --> QC : retroBonne:String

QC -> Q : getRetroactionMauvaise()
Q --> QC : retroMauvaise:String

QC -> Q : getTags()
Q --> QC : tags : List<String>
deactivate Q

QC --> UI : ouvertureMenuModifierQuestion(type, nom, enonce, verite,\nretroBonne, retroMauvaise, tags)
deactivate QC

<-- UI  : ouvertureMenuModifierQuestion() 
deactivate UI

@enduml