@startuml
hide footbox
title RDCU - ajouterQuestionAutreType

participant "qc:QuestionsController" as QC
participant "qs:QuestionsStore" as QS
participant "q:Question" as Q

-> QC : ajouterQuestionAutreType(nom : String, enonce : String, type : String,\n retroactionValide : String, retroactionInvalide : String, tags : String[])

activate QC

QC -> QS : questionNameExists(nom)
activate QS
QS --> QC : nomExiste:boolean
deactivate QS

alt Nom de question unique
  create Q
  QC -> Q : <<create>> Question(nom, enonce, type,\n retroactionValide, retroactionInvalide, tags)
  activate Q
  deactivate Q

  QC -> QS : addQuestion(q)
  activate QS
  deactivate QS

  <-- QC : confirmationAjout(listeQuestions):String
else Nom de question deja utilise
  <-- QC : signalerErreurNomExistant():String
end

deactivate QC

@enduml
