@startuml
hide footbox
title RDCU – Supprimer une question (Demande)

participant "qc:QuestionsController" as QC
participant "qs:QuestionsStore" as QS

-> QC : supprimerQuestion(groupId : String, nom : String)
note right: GRASP: Controller
activate QC

QC -> QS : questionUtiliseeDansQuestionnaire(groupId : String, nom : String)
activate QS
QS --> QC : utilisee : boolean
deactivate QS

alt Question non utilisee dans un questionnaire
  QC -> QS : chercherInfoQuestion(groupId : String, nom : String)
  activate QS
  QS --> QC : question:String
  deactivate QS

  'QC --> UI : afficherInfoQuestionASupprimer(question):String'
  <-- QC : demanderConfirmationSuppression():String

else Question utilisee dans au moins un questionnaire
  QC -> QS : listerQuestionnairesUtilisantQuestion(groupId : String, nom : String)
  activate QS
  QS --> QC : questionnaires : List<Questionnaire>
  deactivate QS

  'QC --> UI : afficherQuestionnairesUtilisantQuestion(questionnaires):String'
  'QC --> UI : desactiverSuppression():boolean'

  <-- QC : suppressionImpossible():String
  deactivate QC
end

@enduml