@startuml
hide footbox
title RDCU - Modifier une question choix multiple

participant "qc:QuestionsController" as QC
participant "q:QuestionChoixMultipleModele" as Q

-> QC ++: modifierQuestionChoixMultiple(nom: string, \n enonce: string,retroactionValide: string,\n retroactionInvalide: string,tags: string[],\n autresDonnees: Record<string, unknown>)
note right: GRASP: Controller

  QC -> QC ++: lireReponsesChoixMultiple(autresDonnees.reponses) : ReponseChoixMultiple[]
  note right: GRASP: Expert
  deactivate QC

  create Q

  QC -> Q : <<create>> QuestionChoixMultipleModele(nom:String, enonce:String,\n retroactionValide:String, retroactionInvalide:String, tags:String[],\n seulementUnChoix:Boolean, reponses:String[])
  note right: GRASP: Creator

<- QC : q:QuestionChoixMultiple 
@enduml