@startuml
hide footbox
title RDCU – Modifier une question

participant "qc:QuestionsController" as QC
participant "qs:QuestionsStore" as QS
participant "q:Question" as Q

-> QC : modifierQuestion(groupId, nom, enonce, type,\nretroactionValide, retroactionInvalide, tags)
note right: GRASP: Controller
activate QC

QC -> QS : questionNameExists(groupId : String, nom : String)
activate QS
QS --> QC : nomExiste : boolean
deactivate QS

alt Nom de question unique (nomExiste == false)
  QC -> Q : modifierQuestion(nom, enonce, type,\nretroactionValide, retroactionInvalide, tags)
  activate Q
  Q --> QC : confirmationModificationQuestion : boolean
  deactivate Q

  QC -> QS : updateQuestion(Q)
  activate QS
  QS --> QC : confirmationModificationQuestionStore : boolean
  deactivate QS

  <-- QC : afficherConfirmationModification(Q)
  deactivate QC

else Nom de question deja utilise (nomExiste == true)

  <-- QC : erreurNomNonUnique():String
  deactivate UI
end

@enduml