@startuml
hide footbox
title RDCU - Afficher la liste des questions

participant "qc:QuestionsController" as QC
participant "cs:CoursStore" as CS

-> QC : consulterQuestionsCours(groupId : String)
note right: GRASP: Controller
activate QC

QC -> CS : getQuestionsForCours(groupId : String)
activate CS
'???'
CS --> QC : questions : List<Question>
deactivate CS

<-- QC : afficherListeQuestions(questions):String
deactivate QC

@enduml