@startuml
hide footbox
title RDCU - Modifier une question Essai

participant "qc:QuestionsController" as QC
participant "q:QuestionEssaiModele" as Q

-> QC ++: modifierQuestionEssai(nom: string, \n enonce: string,retroactionValide: string,\n retroactionInvalide: string,tags: string[])
note right: GRASP: Controller

  create Q

  QC -> Q : <<create>> QuestionEssaiModele(nom:String, enonce:String,\n retroactionValide:String, retroactionInvalide:String, tags:String[],)
  note left: Cree un model puisque c'est techniquement un sosie de la question initiale qui sera remplace
  note right: GRASP: Creator

<- QC : q:QuestionEssai 
@enduml