@startuml MDD_SGB_SGA
skinparam style strictuml
'skinparam backgroundcolor transparent
hide methods
hide empty members
'left to right direction
title Modèle du domaine

skinparam class {
  BackgroundColor<< SGB >> #ddffdd
  backgroundColor<<Itération 1>> #ddffdd
  backgroundColor<<Itération 2>> #ddf9ff
  backgroundColor<<Itération 3>> BLUE
}
hide stereotype


  ' Le concept de "Cours" dans SGA n'est pas un groupe-cours
  class "Question" as question <<Itération 1>> {
  nom : String
  énoncé : String
  ' reponse a la question
  retroactionValide : String
  retroactionInvalide : String
  }
  class "Tags" as tags <<Itération 1>>{
    nom : String
  }
  class "questionVraiFaux" as qvf <<Itération 1>> extends question {
    reponse : boolean
    retroaction : String
  }
  class "questionChoixMultiple" as qcm <<Itération 1>> extends question {
    seulementUnChoix : boolean
  }
  class "reponseChoixMultiple" as rcm <<Itération 1>> {
    retroaction : String
    text : String
    estBonneReponse : boolean
  }
  class "questionMiseEnCorrespondance" as qmc <<Itération 1>> extends question {
    
  }
  class "pairDeCorrespondance" as pdc <<Itération 1>> {
    question : String
    reponse : String
  }
  class "questionReponseCourte" as qrc <<Itération 1>> extends question  {
    reponseAttendue : String
    retroaction : String
  }
  class "questionNumerique" as qn <<Itération 1>> extends question  {
    reponseAttendue : int
    retroaction : String
  }
  class "questionEssai" as qe <<Itération 1>> extends question  {
    
  }
  class "Enseignant" as ens <<Itération 1>> {
    token : String
  }
  class "Cours" as cours <<Itération 1>> {
    idGroupe : String
    jour : String
    heure : String
    activite : String
    mode : String
    local : String
    idEnseignant : String
    idCours : String
    titreCours : String
  }
  class "Etudiant" as etudiant <<Itération 2>>{
    prenom : String
    nom : String
    courriel : String
    codePermanent : String
  }
  class "Questionnaire" as questionnaire <<Itération 2>>{
    nom : String
    description : String
    actif : boolean
  }
  class "PositionQuestion" as position <<Itération 2>>{
    ordre : int
  }

  etudiant "*" -- "*" cours : associé-à >
  cours "1" -- "*" question :contient >
  cours "*" -- "1" ens : est associé-à >
  question "*" -- "*" tags : appartient-à >
  qcm "1" -- "*" rcm : contient >
  qmc "1" -- "*" pdc : contient >
  cours "1" -- "*" questionnaire : contient >
  questionnaire "*" -- "*" question : contient >
  (questionnaire,question) .. position

legend right
    |Color| Type |
    |<#ddffdd>| Itération 1 |
    |<#ddf9ff>| Itération 2 |
    |<#0000FF>| Itération 3 |
endlegend


  'Selon le CU08 
  'class "ReponseQuestionnaire" as reponseQuestionnaire {

  '}
  'etudiant "*" -- "*" questionnaire : répond-à >
  '(etudiant,questionnaire) .. reponseQuestionnaire
@enduml