@startuml MDD
skinparam style strictuml
title Modèle du domaine
class Enseignant{

}
class Cours{
  identifiantGroupe : String
  local : String
  ' Les suivants pouraient etre dans l'horaire
  aDistance : bool
  deJour : bool  
}
class Groupe-cours{

}
class Étudiant{
  prenom : String
  nom : String
  codePermanent : String
  email : String
}
class Université{

}
class Horaire{

}

Enseignant "*" -- "1" Université : Employé par >

Étudiant "*" -- "1" Université : Inscrit à >

Cours "1" -- "1" Horaire :  Suis l' >

Étudiant "*" -- "*" "Groupe-cours" : Inscrit à >

Cours "1" -- "1" "Groupe-cours" : associé à >

@enduml