@startuml MDD_SGB_SGA
skinparam style strictuml
'skinparam backgroundcolor transparent
hide methods
hide empty members
'left to right direction
title Modèle du domaine

skinparam class {
  BackgroundColor<< SGB >> #ddffdd
}
hide stereotype


  ' Le concept de "Cours" dans SGA n'est pas un groupe-cours
  class "Question" as question {
  nom : String
  énoncé : String
  ' reponse a la question
  retroactionValide : String
  retroactionInvalide : String
  }
  class "Tags" as tags {
    nom : String
  }
  class "questionVraiFaux" as qvf extends question {
    reponse : boolean
    retroaction : String
  }
  class "questionChoixMultiple" as qcm extends question {
    seulementUnChoix : boolean
  }
  class "reponseChoixMultiple" as rcm {
    retroaction : String
    text : String
    estBonneReponse : boolean
  }
  class "questionMiseEnCorrespondance" as qmc extends question {
    
  }
  class "pairDeCorrespondance" as pdc {
    question : String
    reponse : String
  }
  class "questionReponseCourte" as qrc extends question {
    reponseAttendue : String
    retroaction : String
  }
  class "questionNumerique" as qn extends question {
    reponseAttendue : int
    retroaction : String
  }
  class "questionEssai" as qe extends question {
    
  }
  class "Enseignant" as ens {
    token : String
  }
  class "cours" as cours {
    sigle : String
    titre : String
  }
  class "Etudiant" as etudiant {
    prenom : String
    nom : String
    courriel : String
    codePermanent : String
  }
  class "InformationCours" as infocours {
    identifiant : String
    jour : String
    local : String
    enPresence : boolean
  }
  class "horaire" as horaire {
    lundi : String
    mardi : String
    mercredi : String
    jeudi : String
    vendredi : String
  }
  class "Questionnaire" as questionnaire {
    nom : String
    description : String
    actif : boolean
  }
  class "PositionQuestion" as position {
    ordre : int
  }

  etudiant "*" -- "*" cours : associé-à >
  infocours "1" -- "1" cours : décrit >
  infocours "1" -- "1" horaire : contient >
  cours "1" -- "*" question :contient >
  cours "*" -- "1" ens : est associé-à >
  question "*" -- "*" tags : appartient-à >
  qcm "1" -- "*" rcm : contient >
  qmc "1" -- "*" pdc : contient >
  cours "1" -- "*" questionnaire : contient >
  questionnaire "*" -- "*" question : contient >
  (questionnaire,question) .. position


  'Selon le CU08 
  'class "ReponseQuestionnaire" as reponseQuestionnaire {

  '}
  'etudiant "*" -- "*" questionnaire : répond-à >
  '(etudiant,questionnaire) .. reponseQuestionnaire
@enduml