@startuml MDD_SGB_SGA
skinparam style strictuml
'skinparam backgroundcolor transparent
hide methods
hide empty members
'left to right direction
title Modèle du domaine

skinparam class {
  BackgroundColor<< SGB >> #ddffdd
}
hide stereotype

package SGB {
  class "Université" as U << SGB >> {}
  class "Enseignant" as En << SGB >> {
    prénom: String
    nom: String
    courriel: String
  }
  class "Étudiant" as Et << SGB >> {
    codePermanent : String
    prénom: String
    nom: String
    courriel: String
  }
  class "Cours" as Cours << SGB >> {
    sigle : String
    titre : String
  }
  class "Catalogue\nCours" as CatalogueCours << SGB >> {}
  class "Groupe\nCours" as GC << SGB >> {
    limiteNbInscriptions : Entier
    idGroupe : String
  }
  class "Bordereau" as Bord << SGB >> {}
  class "Évaluation" as Éval << SGB >> {
    type: String
    idType: Entier
    note: Float
  }
}


U "1" -- "1" CatalogueCours : Offre >
U "1" -- "1..*" Et : Forme >
U "1" -- "1..*" En : Emploie >
CatalogueCours "1" -- "1..*" Cours : Répertorie >
Cours "1" -- "1..*" GC : Décrit >
En "1" -- "*" GC : Enseigne >
Et "1..*" -- "1..*" GC : S'inscrit-dans >
GC "1" -- "1" Bord : Répertorie-evaluations-pour <
Bord "1" -- "*" Éval : Journalise >

' début de SGA
package SGA {
  ' Le concept de "Cours" dans SGA n'est pas un groupe-cours
  class "sga" as sga {
    ' aussi controleur
  }
  class "BanqueDeQuestions" as bq {

  }
  class "Question" as question {
  nom : String
  énoncé : String
  ' reponse a la question
  retroactionValide : String
  retroactionInvalide : String
  }
  class "Tags" as tags {
    nom : String
  }
  class "questionVraiFaux" as qvf extends question {
    reponse : boolean
    retroaction : String
  }
  class "questionChoixMultiple" as qcm extends question {
    seulementUnChoix : boolean
  }
  class "reponseChoixMultiple" as rcm {
    retroaction : String
    text : String
    estBonneReponse : boolean
  }
  class "questionMiseEnCorrespondance" as qmc extends question {
    
  }
  class "pairDeCorrespondance" as pdc {
    question : String
    reponse : String
  }
  class "questionReponseCourte" as qrc extends question {
    reponseAttendue : String
    retroaction : String
  }
  class "questionNumerique" as qn extends question {
    reponseAttendue : int
    retroaction : String
  }
  class "questionEssai" as qe extends question {
    
  }
  class "Enseignant" as ens {
    token : String
  }
  class "cours" as cours {
    sigle : String
    titre : String
  }
  class "Etudiant" as etudiant {
    prenom : String
    nom : String
    courriel : String
    codePermanent : String
  }
  class "InformationCours" as infocours {
    identifiant : String
    jour : String
    local : String
    enPresence : boolean
  }
  class "horaire" as horaire {
    lundi : String
    mardi : String
    mercredi : String
    jeudi : String
    vendredi : String
  }
  









  sga "0..1" -- "1" GC : Est-un-support-des-activités-du >
  etudiant "*" -- "*" cours : associé-à >
  ens "1" -- "*" sga : utilis >
  infocours "1" -- "1" cours : décrit >
  infocours "1" -- "1" horaire : contient >
  cours "1" -- "1" bq :contient >
  bq "1" -- "*" question : contient >
  cours "*" -- "1" ens : est associé-à >
  question "*" -- "*" tags : appartient-à >
  qcm "1" -- "*" rcm : contient >
  qmc "1" -- "*" pdc : contient >

}
@enduml