@startuml
hide footbox

title RDCU pour jouer

participant ":JeuDeDes" as J
participant "joueurs:\nMap<String,Joueur>" as M
participant "d1:De" as D1
participant "d2:De" as D2
participant "j:Joueur" as P

-> J : jouer(nom : String):JSON
activate J

note right
  selon Contrôleur
end note

J -> M : j = chercher(nom : String):Joueur
activate M
J <-- M : j:Joueur
deactivate M

note right
  selon Transformer ID en objets
end note

J -> D1 : brasser():int
activate D1

note right
  selon Expert
end note

J <-- D1 : valeur1:Int
deactivate D1

J -> D2 : brasser():int
activate D2

note right
  selon Expert
end note

J <-- D2 : valeur2:Int
deactivate D2

note right
  selon Expert
end note

opt "valeur1 + valeur2 == 7"
    J -> P : gagner():void
    activate P
    note right
      selon Expert
    end note
    deactivate P
end

J -> P : getNombreParties():int

activate P
note right
  selon Expert
end note

J <-- P: nombrePartie:int
deactivate P

J -> P : g = getNombrePartiesGagnees():int
activate P
note right
   selon Expert
end note
    
J <-- P: nombrePartieGagnees:int
deactivate P

<-- J : resulats:JSON
@enduml