@startuml
hide footbox

title RDCU pour jouer

participant ":JeuDeDes" as J
participant "joueurs:\nMap<String,Joueur>" as M

-> J : terminerJeu(nom : String):void
activate J

note right
  selon Contrôleur
end note

J -> M : delete(nom : String):void
activate M
deactivate M

deactivate J
@enduml