@startuml
title CU01c - Retirer un cours
actor ":Enseignant" as e
participant ":Systeme" as s

e->s : supprimerCours(idCours : String);

s-->>e : Demande de confirmation

e->s : confirmerSuppressionCours();

s-->>e : Liste des cours et message \nde confirmation de la suppression du cours

@enduml