@startuml
title CU01a - Ajouter un cours
actor ":Enseignant" as e
participant ":Systeme" as s

e->s : demarrerAjoutCours();

s-->>e : liste des groupes-cours assignés à l'enseignant
loop Tant qu'un cours correspondant au groupe-cours sélectionné existe déjà.
e->s : sélectionnerGroupeCours(idGroupe : String)
end loop
s-->>e : Informations du cours associé au groupe-cours sélectionné \net la liste des Étudiants inscrits dans ce groupeCours

@enduml