@startuml
title CU01a - Ajouter un cours
actor ":Enseignant" as e
participant ":Systeme" as s

e->s : demarrerAjoutCours()

s-->>e : liste des groupes-cours assignés à l'enseignant \nqui ne sont pas déjà ajoutés

e->s : sélectionnerGroupeCours(idGroupe : String)

s-->>e : confirmation d'ajout du cours

@enduml
