@startuml
title Afficher - Détails d'un cours
skinparam Style strictuml
skinparam sequenceMessageAlign center

participant "cc:coursController"  as cc
participant "sga:accesSGA" as sga

 -> cc : afficherDetailsCours(idGroupe: String) : cours
note right: GRASP: Controller
activate cc
cc -> sga : getEtudiantsParGroupe(idGroupe: String) : Étudiant[]
note right: GRASP: Expert
activate sga
sga -->> cc : ListeEtudiants : Étudiant[]

deactivate cc
@enduml