@startuml
hide footbox
title RDCU - Confirmation de retrait d'un cours

participant ":CoursController" as ctrl
participant ":CoursModele" as modele

-> ctrl : suppressionCours(idCours:String)
note right: GRASP: Controller
activate ctrl
ctrl -> modele : retirerCoursStocke(idCours:String)
note right: GRASP: Expert
activate modele
modele -->> ctrl : suppressionOK
deactivate modele
<<-- ctrl : listeCours + messageSuppressionConfirmee
deactivate ctrl
@enduml
