@startuml
hide footbox
title RDCU – Retirer un cours

participant "cc:coursController" as cc

activate cc
-> cc : retirerCours(idCours : String)
note right: GRASP: Controller

cc -> cc : idCours = idCours
note right: GRASP: Expert

<-- cc : confirmerLaSuppression()

@enduml