@startuml
hide footbox
title RDCU –  Confirmation de retrait d'un cours

participant "cc:controlleurCours" as cc
participant "cs:coursStore" as cs

activate cc
 -> cc : confirmerSuppressionCours()
note right: GRASP: Controller

cc -> cc : suppressionCours(idCours : String)
note right: GRASP: Expert

cc -> cs : retirerCoursStocke(idCours : String)
note right: GRASP: Expert
activate cs
cs --> cc : coursRestant()
deactivate cs

<-- cc: messageSuppressionConfirmer()

@enduml