@startuml
title RDCU - Demarrer Ajout Cours
skinparam Style strictuml
skinparam sequenceMessageAlign center

participant ":CoursController" as coursController

-> coursController : demarrerAjoutCours()
activate coursController
coursController -->> coursController : appel service SGB (boite noire)
<<-- coursController : listeGC:Groupe-Cours[]
deactivate coursController
@enduml
