@startuml
hide footbox
title RDCU - selectionnerGroupeCours(idGroupe : String)

participant ": Enseignant" as E
participant "sga : accesSga" as S
participant "c : Cours" as C

-> E : selectionnerGroupeCours(idGroupe : String)
activate E

E -> S : getCours(idGroupe : String, token:string)
activate S
S -> C ** : <<create>> Cours\n(idGroupe:String, token:string)


S -->> E : c : Cours
deactivate S

E -> E : associerCoursAEnseignant(C)
activate E
deactivate E
deactivate E
@enduml
