@startuml
hide footbox
title RDCU – Retirer un cours

participant Enseignant as Ens

activate Ens
 -> Ens : retirerCours(idCours : String)
Ens -> Ens : idCours = idCours
activate Ens
deactivate Ens
deactivate Ens


@enduml