@startuml
title RDCU - afficher liste des cours
skinparam Style strictuml
skinparam sequenceMessageAlign center

participant ":CoursController" as coursController
participant ":CoursModele" as coursModele

-> coursController : afficherListeCours() : Cours[]
activate coursController
coursController -> coursModele : obtenirCoursStockesPourProf(idEnseignant:String): Cours[]
activate coursModele
coursModele -->> coursController : createdGroups:Cours[]
deactivate coursModele
coursController -->> coursController : filtrer les groupes disponibles
<<-- coursController : listeCours:cours[]
deactivate coursController
@enduml
