@startuml
title RDCU - Demarrer Ajout Cours
skinparam Style strictuml
skinparam sequenceMessageAlign center

participant ":CoursController" as coursController
participant ":SgbClient" as sgbClient

-> coursController : demarrerAjoutCours(teacherId : String, token : String)
note right: GRASP: Controller
activate coursController
coursController -> sgbClient : getCours(teacherId, token)
activate sgbClient
sgbClient -->> coursController : listeCours : Cours[]
deactivate sgbClient
<<-- coursController : listeCours : Cours[]
deactivate coursController
@enduml
