@startuml
title Afficher - Détails d'un cours
skinparam Style strictuml
skinparam sequenceMessageAlign center

participant ":Enseignant"  as enseignant
participant "sga:accesSGA" as sga

 -> enseignant : afficherDetailsCours(idGroupe: String) : cours
note right: controlleur
activate enseignant
enseignant -> sga : getEtudiantsParGroupe(idGroupe: String) : Étudiant[]
sga -->> enseignant : ListeEtudiants : Étudiant[]

deactivate enseignant
@enduml