@startuml
hide footbox
title RDCU - selectionnerGroupeCours(idGroupe : String)

participant "cc:coursController" as cc
participant "sga : accesSga" as S
participant "c : Cours" as C

-> cc : selectionnerGroupeCours(idGroupe : String)
note right: GRASP: Controller
activate cc

cc -> S : getCours(idGroupe : String, token:string)
note right: GRASP: Expert
activate S
S -> C ** : <<create>> Cours\n(idGroupe:String, token:string)
note right: GRASP: Creator

S -->> cc : c : Cours
deactivate S
@enduml
