@startuml
title RDCU - Afficher liste des cours
skinparam Style strictuml
skinparam sequenceMessageAlign center

participant ":CoursController" as coursController
participant ":CoursModele" as coursModele

-> coursController : afficherListeCours() : Cours[]
note right: GRASP: Controller
activate coursController
coursController -> coursModele : obtenirCoursStockesPourProf(idEnseignant:String): Cours[]
note right: GRASP: Expert
activate coursModele
coursModele -->> coursController : createdGroups:Cours[]
deactivate coursModele
coursController -->> coursController : filtrer les groupes disponibles
<<-- coursController : listeCours:cours[]
deactivate coursController
@enduml
