@startuml
title Afficher - Details d'un cours
skinparam Style strictuml
skinparam sequenceMessageAlign center

participant ":CoursController" as coursController
participant ":CoursModele" as coursModele

-> coursController : afficherDetailsCours(idCours:String) : Cours
activate coursController
coursController -> coursModele : obtenirCoursStockeParIdGroupe(idCours:String) : Cours
coursModele -->> coursController : cours:Cours
coursController -> coursModele : obtenirQuestionsDuCours(idCours:String) : Question[]
coursModele -->> coursController : questions:Question[]
<<-- coursController : detailsCours + etudiants + questions
deactivate coursController
@enduml
