@startuml
title CU05a - Ajouter un questionnaire
actor ":Enseignant" as e
participant ":Systeme" as s
e->s : gererQuestionnaires()
s-->>e : Liste des questionnaires associes au cours
e->s : ajouterQuestionnaire(nom:String, description:String, actif:bool)
s-->>e : Confirmation de l'ajout et liste de tags de Questions
e->s : selectionnerTag(nom : String)
loop tant que l'enseignant n'a pas terminé l'ajout de questions.
s-->>e : Questions correspondant au tag et nombre de questionnaires\n auxquels ces questions ont déjà été ajoutées.
'important de mettre a jout le nombre de quetionnaires auquel les questions ont déjé été ajoutées apres un ajout
e->s : ajouterQuestion(nomQuestions : String[])
'Pas de fonction du coté du système
e->s : sauvegarderQuestionnaire()
s-->>e : Confirmation de la sauvegarde du questionnaire
end loop
@enduml
