@startuml
title CU05c - Modifier un questionnaire

actor ":Enseignant" as e
participant ":Systeme" as s

e->s : selectionModifierQuestionnaire(nom : String)
s-->>e : les details du questionnaire
alt L'enseignant associe de nouvelles questions
e->s : obtenirTags()
s-->>e : Liste de tags de Questions
e->s : selectionnerTag(nom : String)
loop tant que l'enseignant n'a pas terminé l'ajout de questions.
s-->>e : Questions correspondant au tag et nombre de questionnaires\n auxquels ces questions ont déjà été ajoutées.
'important de mettre a jout le nombre de quetionnaires auquel les questions ont déjé été ajoutées apres un ajout
e->s : ajouterQuestion(nomQuestion : String)
'Pas de fonction du coté du système
end loop
else L'enseignant dissocie des questions
e->s : dissocierQuestion(nomQuestion : String)
else L'enseignant modifie l'ordre des questions
e->s : modifierOrdreQuestions(nomQuestion: String, nouvellePosition : int)
end alt
e->s : modifierQuestionnaire(nom:String, description:String, actif:boolean)
s-->>e : Confirmation de la sauvegarde des modifications
@enduml
