@startuml
title RDCU Ajouter une question

participant ":QuestionnaireController" as controller
participant ":QuestionnaireModele" as questionnaireModele
participant "questionnaireTemp:Questionnaire" as temp

-> controller : ajouterQuestion(nomQuestion:String)
    note right: GRASP: Controller
    activate controller
    controller -> questionnaireModele ++: ajouterQuestion(nomQuestion:String)
    note right: GRASP: Expert
    questionnaireModele -> questionnaireModele ++: question = obtenirQuestionParNom(nomQuestion:String):Question
    note right: GRASP: Expert
    deactivate questionnaireModele
    questionnaireModele -> temp ++: ajouterQuestion(question:Question)
    note right: GRASP: Expert
    deactivate temp
    deactivate questionnaireModele
    deactivate controller

@enduml