@startuml
hide footbox
title RDCU - Dissocier une question du questionnaire

participant ":QuestionnaireController" as controller
participant ":QuestionnaireModele" as questionnaireModele
participant "questionnaireTemp:Questionnaire" as temp

-> controller : dissocierQuestion(nomQuestion:String)
    note right: GRASP: Controller
    activate controller
    controller -> questionnaireModele ++: dissocierQuestion(nomQuestion:String)
    note right: GRASP: Expert
    questionnaireModele -> questionnaireModele ++: question = obtenirQuestionParNom(nomQuestion:String):Question
    note right: GRASP: Expert
    deactivate questionnaireModele
    questionnaireModele -> temp ++: retirerQuestion(question:Question)
    note right: GRASP: Expert
    questionnaireModele <-- temp : Void
    deactivate temp
    controller <-- questionnaireModele : Void
    deactivate questionnaireModele
    <-- controller : Void
    deactivate controller

@enduml