@startuml
title CU05a - RDCU Sauvegarder un questionnaire

participant ":QuestionnaireController" as controller
participant ":QuestionnaireModele" as questionnaireModele
participant "q:Questionnaire" as questionnaire
participant "questions:Question[]" as tab

-> controller : sauvegarderQuestionnaire():boolean
note right: GRASP: Controller
activate controller
controller -> questionnaireModele ++: sauvegarderQuestionnaire():boolean
note right: GRASP: Expert
questionnaireModele -> questionnaire ++: ajouterQuestions(questions:Question[])
note right: GRASP: Expert
deactivate questionnaire
note bottom: effacer le contenu de questions apres la sauvegarde -->
questionnaireModele --> controller : confirmerSauvegarde:boolean
deactivate questionnaireModele
<-- controller : confirmerSauvegarde : boolean
deactivate controller

@enduml