@startuml
title RDCU Selectionner un tag

participant ":QuestionnaireController" as controller
participant ":QuestionnaireModele" as questionnaireModele

-> controller : selectionnerTag(nomTag:String):Questions[]
note right: GRASP: Controller
activate controller
'peut etre changer la classe qui recoit obtenirQuestionsParTag() pour ne pas que le modele de questionnaire soit oblige de connaitre les tags
controller -> questionnaireModele : obtenirQuestionsParTag(groupeId:String, nomTag:String):Questions[]
note right: GRASP: Expert
activate questionnaireModele
questionnaireModele --> controller : questions:Questions[]
deactivate questionnaireModele
<-- controller : questionsDuTag:Questions[]
deactivate controller

@enduml