@startuml
title RDCU Ajouter un questionnaire

participant ":QuestionnaireController" as controller
participant ":QuestionnaireModele" as questionnaireModele
participant "q:Questionnaire" as questionnaire

-> controller : ajouterQuestionnaire(nom:String, description:String, actif:boolean):String
note right: GRASP: Controller
activate controller
controller -> questionnaireModele : creerQuestionnaire(groupeId:String, nom:String, description:String, actif:boolean):Questionnaire
note right: GRASP: Expert
activate questionnaireModele
create questionnaire
questionnaireModele -> questionnaire : q = new Questionnaire(nom:String, description:String, actif:boolean)
note right: GRASP: Creator
activate questionnaire
questionnaire --> questionnaireModele : q:Questionnaire
deactivate questionnaire
questionnaireModele -> questionnaireModele ++: ajouterQuestionnaire(q:Questionnaire)
note right
GRASP: Expert
(ajouter le questionnaire dans le data.json pour questionnaires)
end note
deactivate questionnaireModele
questionnaireModele --> controller : q:Questionnaire
deactivate questionnaireModele
'peut etre changer la classe qui recoit obtenirListeTagsDesQuestions() pour ne pas que le modele de questionnaire soit oblige de connaitre les tags
controller -> questionnaireModele : obtenirListeTagsDesQuestions(groupeId:String):String[]
note right: GRASP: Expert
activate questionnaireModele
questionnaireModele --> controller : tags:String[]
deactivate questionnaireModele
<-- controller : confirmerAjoutEtAfficherTagsJSON:String
deactivate controller

@enduml
